name: auto merge renovate
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
on:
  pull_request:
    branches:
      - main
    types:
      - opened
defaults:
  run:
    shell: bash
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ startsWith( github.head_ref , 'renovate') }}
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        with:
          app-id: ${{ vars.BOT_GITHUB_APP_ID }}
          private-key: ${{ secrets.BOT_GITHUB_APP_PRIVATE_KEY }}
      - name: Auto merge
        uses: otakakot/github-actions/composite/auto-merge@main
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
